import type { SourceConfig } from '@/types'

export const SOURCES: SourceConfig[] = [
  // ── 글로벌 보건기구 ──────────────────────────────────────────
  {
    id: 'who',
    name: 'WHO',
    feedUrl: 'https://www.who.int/rss-feeds/news-releases-en.xml',
    type: 'rss',
    category: 'global_health_org',
    language: 'en',
  },
  {
    id: 'cdc',
    name: 'CDC',
    feedUrl: 'https://www2.cdc.gov/podcasts/feeds/media.rss',
    type: 'rss',
    category: 'global_health_org',
    language: 'en',
  },
  {
    id: 'nih',
    name: 'NIH',
    feedUrl: 'https://www.nih.gov/news-events/news-releases',
    type: 'html',
    category: 'global_health_org',
    language: 'en',
    selectors: {
      item: '.news-release-teaser, .views-row',
      title: 'h3 a, h2 a',
      link: 'h3 a, h2 a',
      date: 'time, .date-display-single',
      linkBase: 'https://www.nih.gov',
    },
  },
  {
    id: 'ecdc',
    name: 'ECDC',
    feedUrl: 'https://www.ecdc.europa.eu/en/rss.xml',
    type: 'rss',
    category: 'global_health_org',
    language: 'en',
  },

  // ── 글로벌 의학 저널 ──────────────────────────────────────────
  {
    id: 'pubmed',
    name: 'PubMed',
    feedUrl: 'https://pubmed.ncbi.nlm.nih.gov/rss/search/?term=medicine+health&EntrezSystem2.PEntrez.PubMed.Pubmed_ResultsPanel.Pubmed_RVDocSum=abstract&dr=1&count=20',
    type: 'rss',
    category: 'global_journal',
    language: 'en',
  },
  {
    id: 'lancet',
    name: 'The Lancet',
    feedUrl: 'https://www.thelancet.com/rssfeed/lancet_current.xml',
    type: 'rss',
    category: 'global_journal',
    language: 'en',
  },
  {
    id: 'nejm',
    name: 'NEJM',
    feedUrl: 'https://www.nejm.org/action/showFeed?jc=nejmoa&type=etoc&feed=rss',
    type: 'rss',
    category: 'global_journal',
    language: 'en',
  },
  {
    id: 'jama',
    name: 'JAMA',
    feedUrl: 'https://jamanetwork.com/rss/site_3/67.xml',
    type: 'rss',
    category: 'global_journal',
    language: 'en',
  },
  {
    id: 'nature_medicine',
    name: 'Nature Medicine',
    feedUrl: 'https://www.nature.com/nm.rss',
    type: 'rss',
    category: 'global_journal',
    language: 'en',
  },
  {
    id: 'nejm_ai',
    name: 'NEJM AI',
    feedUrl: 'https://ai.nejm.org/action/showFeed?jc=aioa&type=etoc&feed=rss',
    type: 'rss',
    category: 'global_journal',
    language: 'en',
  },

  // ── 글로벌 의료 AI ──────────────────────────────────────────
  {
    id: 'stanford_hai',
    name: 'Stanford HAI',
    feedUrl: 'https://hai.stanford.edu/news/feed',
    type: 'rss',
    category: 'global_medical_ai',
    language: 'en',
  },
  {
    id: 'google_health',
    name: 'Google Health',
    feedUrl: 'https://blog.google/technology/health/',
    type: 'html',
    category: 'global_medical_ai',
    language: 'en',
    selectors: {
      item: 'article, [class*="article-card"]',
      title: 'h3, h2, [class*="article__title"]',
      link: 'a',
      date: 'time',
      linkBase: '',
    },
  },
  {
    id: 'microsoft_health',
    name: 'Microsoft Health',
    feedUrl: 'https://blogs.microsoft.com/blog/category/health-life-sciences/feed/',
    type: 'rss',
    category: 'global_medical_ai',
    language: 'en',
  },
  {
    id: 'medicalxpress',
    name: 'MedicalXpress',
    feedUrl: 'https://medicalxpress.com/rss-feed/',
    type: 'rss',
    category: 'global_medical_ai',
    language: 'en',
  },
  {
    id: 'reuters',
    name: 'Reuters Health',
    feedUrl: 'https://feeds.reuters.com/reuters/healthNews',
    type: 'rss',
    category: 'global_medical_ai',
    language: 'en',
  },

  // ── 국내 정부·공공기관 ──────────────────────────────────────────
  {
    id: 'kdca',
    name: '질병관리청',
    feedUrl: 'https://www.kdca.go.kr/board/board.es?mid=a20501000000&bid=0015',
    type: 'html',
    category: 'korea_gov',
    language: 'ko',
    selectors: {
      item: 'table.board_list tbody tr, .bbs-list tbody tr',
      title: 'td.title a, td a.title, .title a',
      link: 'td.title a, td a.title, .title a',
      date: 'td:last-child, .date',
      linkBase: 'https://www.kdca.go.kr',
    },
  },
  {
    id: 'mohw',
    name: '보건복지부',
    feedUrl: 'https://www.mohw.go.kr/react/al/salalView.jsp?menuId=04&sSubCode=&boardId=140&searchField=&searchWord=&page=1',
    type: 'html',
    category: 'korea_gov',
    language: 'ko',
    selectors: {
      item: 'ul.bbs_list li, .board-list li, table tbody tr',
      title: 'a.tit, .subject a, td.title a',
      link: 'a.tit, .subject a, td.title a',
      date: '.date, td:last-child',
      linkBase: 'https://www.mohw.go.kr',
    },
  },
  {
    id: 'mfds',
    name: '식품의약품안전처',
    feedUrl: 'https://www.mfds.go.kr/brd/m_99/list.do',
    type: 'html',
    category: 'korea_gov',
    language: 'ko',
    selectors: {
      item: 'table.board_list tbody tr, .bbs-list tbody tr',
      title: 'td.title a, td a',
      link: 'td.title a, td a',
      date: '.date, td:last-child',
      linkBase: 'https://www.mfds.go.kr',
    },
  },
  {
    id: 'hira',
    name: '건강보험심사평가원',
    feedUrl: 'https://www.hira.or.kr/bbsDummy.do?pgmid=HIRAA020000000000&brdScnBltNo=4&pageIndex=1',
    type: 'html',
    category: 'korea_gov',
    language: 'ko',
    selectors: {
      item: 'table tbody tr, .board-list tbody tr',
      title: 'td.title a, td a.title',
      link: 'td.title a, td a.title',
      date: '.date, td:nth-last-child(2)',
      linkBase: 'https://www.hira.or.kr',
    },
  },
  {
    id: 'khidi',
    name: '한국보건산업진흥원',
    feedUrl: 'https://www.khidi.or.kr/kps/diss/notice/boardView',
    type: 'html',
    category: 'korea_gov',
    language: 'ko',
    selectors: {
      item: 'table tbody tr, .board-list li',
      title: 'td.title a, .subject a',
      link: 'td.title a, .subject a',
      date: '.date, td:last-child',
      linkBase: 'https://www.khidi.or.kr',
    },
  },

  // ── 국내 의료 AI 기업 ──────────────────────────────────────────
  {
    id: 'lunit',
    name: '루닛',
    feedUrl: 'https://www.lunit.io/ko/blog',
    type: 'html',
    category: 'korea_medical_ai',
    language: 'ko',
    selectors: {
      item: 'article, .blog-card, [class*="PostCard"]',
      title: 'h2, h3, [class*="title"]',
      link: 'a',
      date: 'time, .date, [class*="date"]',
      linkBase: 'https://www.lunit.io',
    },
  },
  {
    id: 'vuno',
    name: '뷰노',
    feedUrl: 'https://www.vuno.co/blog',
    type: 'html',
    category: 'korea_medical_ai',
    language: 'ko',
    selectors: {
      item: 'article, .post-card, [class*="blog-item"]',
      title: 'h2, h3, .post-title',
      link: 'a',
      date: 'time, .date',
      linkBase: 'https://www.vuno.co',
    },
  },
  {
    id: 'dhp',
    name: '디지털헬스케어파트너스',
    feedUrl: 'https://www.digitalhealthcarepartners.com/',
    type: 'html',
    category: 'korea_medical_ai',
    language: 'ko',
    selectors: {
      item: 'article, .post, .entry',
      title: 'h2 a, h3 a, .entry-title a',
      link: 'h2 a, h3 a, .entry-title a',
      date: 'time, .entry-date',
      linkBase: '',
    },
  },

  // ── 국내 의료 전문 뉴스 ──────────────────────────────────────────
  {
    id: 'hitnews',
    name: '히트뉴스',
    feedUrl: 'https://www.hitnews.co.kr/rss/allArticle.xml',
    type: 'rss',
    category: 'korea_medical_news',
    language: 'ko',
  },
  {
    id: 'docdocdoc',
    name: '청년의사',
    feedUrl: 'http://www.docdocdoc.co.kr/rss/allArticle.xml',
    type: 'rss',
    category: 'korea_medical_news',
    language: 'ko',
  },
  {
    id: 'medicaltimes',
    name: '메디칼타임즈',
    feedUrl: 'https://www.medicaltimes.com/rss/allArticle.xml',
    type: 'rss',
    category: 'korea_medical_news',
    language: 'ko',
  },
  {
    id: 'hkn24',
    name: '헬스코리아뉴스',
    feedUrl: 'https://www.hkn24.com/rss/allArticle.xml',
    type: 'rss',
    category: 'korea_medical_news',
    language: 'ko',
  },
]
